_wandb:
    value:
        cli_version: 0.21.0
        e:
            bm4fg3yk3ccu18ob9vxv6ue4ll2qoghm:
                codePath: yinglong_eval.py
                codePathLocal: yinglong_eval.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "135087439872"
                        used: "13284745216"
                email: mpgee@usc.edu
                executable: /u/mgee2/.conda/envs/gift/bin/python
                git:
                    commit: df9b1350566dada5eb7f8b4523db3f514b70251f
                    remote: https://github.com/mpg05883/gift-eval.git
                gpu: NVIDIA A40
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "48305799168"
                      name: NVIDIA A40
                      uuid: GPU-0c66e9aa-ecc5-b680-c6ea-38253ddfe8ea
                host: gpub001.delta.ncsa.illinois.edu
                memory:
                    total: "270174883840"
                os: Linux-4.18.0-477.95.1.el8_8.x86_64-x86_64-with-glibc2.28
                program: /projects/beei/mgee2/gift-eval/yinglong_eval.py
                python: CPython 3.11.11
                root: /projects/beei/mgee2/gift-eval
                slurm:
                    cluster_name: delta
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x0000000000000001
                    cpu_bind_list: "0x0000000000000001"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "1"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gpus_per_node: "1"
                    gtids: "0"
                    job_account: beei-delta-gpu
                    job_cpus_per_node: "1"
                    job_end_time: "1754528081"
                    job_gid: "202"
                    job_group: grp_202
                    job_id: "11354258"
                    job_name: bash
                    job_nodelist: gpub001
                    job_num_nodes: "1"
                    job_partition: gpuA40x4-interactive
                    job_qos: beei-delta-gpu
                    job_start_time: "1754524481"
                    job_uid: "77057"
                    job_user: mgee2
                    jobid: "11354258"
                    launch_node_ipaddr: 141.142.253.40
                    localid: "0"
                    mem_per_node: "102400"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpub001
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "40355"
                    pty_win_col: "226"
                    pty_win_row: "27"
                    srun_comm_host: 141.142.253.40
                    srun_comm_port: "46199"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "46199"
                    step_nodelist: gpub001
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /projects/beei/mgee2/gift-eval
                    submit_host: dt-login01.delta.ncsa.illinois.edu
                    task_pid: "4066392"
                    tasks_per_node: "1"
                    topology_addr: ss00.ss09.gpub001
                    topology_addr_pattern: switch.switch.node
                    umask: "0022"
                startedAt: "2025-08-06T23:57:28.211386Z"
                writerId: bm4fg3yk3ccu18ob9vxv6ue4ll2qoghm
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 15
                - 49
                - 51
                - 53
                - 71
                - 103
                - 105
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 15
                - 49
                - 51
                - 53
                - 71
                - 103
                - 105
                - 106
            "3":
                - 13
                - 15
            "4": 3.11.11
            "5": 0.21.0
            "6": 4.49.0
            "12": 0.21.0
            "13": linux-x86_64
