- term: short
  names:
  - bull
  - cmip6_1885
  - era5_1991
  - SHMETRO
  - era5_2006
  - BEIJING_SUBWAY_30MIN
  - gfc12_load
  - buildings_900k
  - london_smart_meters_with_missing
  - residential_pv_power
  - PEMS_BAY
  - wind_power
  - cmip6_1975
  - elecdemand
  - wiki-rolling_nips
  - spain
  - cdc_fluview_who_nrevss
  - covid_mobility
  - monash_m3_quarterly
  - era5_2015
  - alibaba_cluster_trace_2018
  - cmip6_1930
  - uber_tlc_hourly
  - era5_2012
  - cmip6_1940
  - bdg-2_rat
  - era5_2018
  - largest_2020
  - cmip6_1875
  - cmip6_1905
  - borg_cluster_data_2011
  - tourism_yearly
  - traffic_weekly
  - largest_2018
  - PEMS07
  - era5_2001
  - cif_2016_6
  - era5_1996
  - bdg-2_panther
  - cmip6_1985
  - monash_m3_yearly
  - bitcoin_with_missing
  - era5_1998
  - era5_1992
  - favorita_sales
  - cmip6_1965
  - hog
  - era5_2005
  - cmip6_1850
  - PEMS03
  - cmip6_1920
  - covid19_energy
  - LOS_LOOP
  - cmip6_1895
  - tourism_quarterly
  - extended_web_traffic_with_missing
  - subseasonal_precip
  - cmip6_2005
  - era5_2016
  - azure_vm_traces_2017
  - taxi_30min
  - favorita_transactions
  - smart
  - kdd2022
  - gfc17_load
  - cif_2016_12
  - era5_2011
  - borealis
  - godaddy
  - cmip6_1995
  - vehicle_trips_with_missing
  - nn5_weekly
  - era5_2002
  - pedestrian_counts
  - era5_2008
  - PEMS04
  - cmip6_1950
  - ideal
  - cmip6_1865
  - residential_load_power
  - era5_1995
  - cmip6_1915
  - cmip6_1855
  - beijing_air_quality
  - era5_2000
  - cmip6_1925
  - china_air_quality
  - kaggle_web_traffic_weekly
  - cdc_fluview_ilinet
  - era5_1997
  - cmip6_1960
  - cmip6_2000
  - era5_2013
  - nn5_daily_with_missing
  - largest_2021
  - cmip6_1890
  - largest_2019
  - sunspot_with_missing
  - m5
  - elf
  - era5_1989
  - cmip6_1990
  - cockatoo
  - era5_2014
  - cmip6_1860
  - era5_1990
  - fred_md
  - cmip6_1910
  - monash_m3_other
  - era5_2007
  - cmip6_1955
  - subseasonal
  - traffic_hourly
  - monash_m3_monthly
  - cmip6_2010
  - era5_2009
  - wind_farms_with_missing
  - era5_2003
  - gfc14_load
  - project_tycho
  - bdg-2_bear
  - m1_monthly
  - cmip6_1880
  - era5_1994
  - era5_2010
  - cmip6_1935
  - australian_electricity_demand
  - m1_quarterly
  - pdb
  - lcl
  - cmip6_1970
  - oikolab_weather
  - cmip6_1870
  - cmip6_1900
  - largest_2017
  - tourism_monthly
  - HZMETRO
  - era5_2017
  - cmip6_1945
  - uber_tlc_daily
  - era5_1993
  - era5_1999
  - cmip6_1980
  - weather
  - rideshare_with_missing
  - PEMS08
  - era5_2004
  - sceaux
  - solar_power
  - m1_yearly
  - bdg-2_fox
  - Q-TRAFFIC
- term: medium
  names:
  - bull
  - cmip6_1885
  - era5_1991
  - SHMETRO
  - era5_2006
  - BEIJING_SUBWAY_30MIN
  - gfc12_load
  - buildings_900k
  - london_smart_meters_with_missing
  - residential_pv_power
  - PEMS_BAY
  - wind_power
  - cmip6_1975
  - elecdemand
  - wiki-rolling_nips
  - spain
  - cdc_fluview_who_nrevss
  - covid_mobility
  - monash_m3_quarterly
  - era5_2015
  - alibaba_cluster_trace_2018
  - cmip6_1930
  - uber_tlc_hourly
  - era5_2012
  - cmip6_1940
  - bdg-2_rat
  - era5_2018
  - largest_2020
  - cmip6_1875
  - cmip6_1905
  - borg_cluster_data_2011
  - tourism_yearly
  - traffic_weekly
  - largest_2018
  - PEMS07
  - era5_2001
  - cif_2016_6
  - era5_1996
  - bdg-2_panther
  - cmip6_1985
  - monash_m3_yearly
  - bitcoin_with_missing
  - era5_1998
  - era5_1992
  - favorita_sales
  - cmip6_1965
  - hog
  - era5_2005
  - cmip6_1850
  - PEMS03
  - cmip6_1920
  - covid19_energy
  - LOS_LOOP
  - cmip6_1895
  - tourism_quarterly
  - extended_web_traffic_with_missing
  - subseasonal_precip
  - cmip6_2005
  - era5_2016
  - azure_vm_traces_2017
  - taxi_30min
  - favorita_transactions
  - smart
  - kdd2022
  - gfc17_load
  - cif_2016_12
  - era5_2011
  - borealis
  - godaddy
  - cmip6_1995
  - vehicle_trips_with_missing
  - nn5_weekly
  - era5_2002
  - pedestrian_counts
  - era5_2008
  - PEMS04
  - cmip6_1950
  - ideal
  - cmip6_1865
  - residential_load_power
  - era5_1995
  - cmip6_1915
  - cmip6_1855
  - beijing_air_quality
  - era5_2000
  - cmip6_1925
  - china_air_quality
  - kaggle_web_traffic_weekly
  - cdc_fluview_ilinet
  - era5_1997
  - cmip6_1960
  - cmip6_2000
  - era5_2013
  - nn5_daily_with_missing
  - largest_2021
  - cmip6_1890
  - largest_2019
  - sunspot_with_missing
  - m5
  - elf
  - era5_1989
  - cmip6_1990
  - cockatoo
  - era5_2014
  - cmip6_1860
  - era5_1990
  - fred_md
  - cmip6_1910
  - monash_m3_other
  - era5_2007
  - cmip6_1955
  - subseasonal
  - traffic_hourly
  - monash_m3_monthly
  - cmip6_2010
  - era5_2009
  - wind_farms_with_missing
  - era5_2003
  - gfc14_load
  - project_tycho
  - bdg-2_bear
  - m1_monthly
  - cmip6_1880
  - era5_1994
  - era5_2010
  - cmip6_1935
  - australian_electricity_demand
  - m1_quarterly
  - pdb
  - lcl
  - cmip6_1970
  - oikolab_weather
  - cmip6_1870
  - cmip6_1900
  - largest_2017
  - tourism_monthly
  - HZMETRO
  - era5_2017
  - cmip6_1945
  - uber_tlc_daily
  - era5_1993
  - era5_1999
  - cmip6_1980
  - weather
  - rideshare_with_missing
  - PEMS08
  - era5_2004
  - sceaux
  - solar_power
  - m1_yearly
  - bdg-2_fox
  - Q-TRAFFIC
- term: long
  names:
  - bull
  - cmip6_1885
  - era5_1991
  - SHMETRO
  - era5_2006
  - BEIJING_SUBWAY_30MIN
  - gfc12_load
  - buildings_900k
  - london_smart_meters_with_missing
  - residential_pv_power
  - PEMS_BAY
  - wind_power
  - cmip6_1975
  - elecdemand
  - wiki-rolling_nips
  - spain
  - cdc_fluview_who_nrevss
  - covid_mobility
  - monash_m3_quarterly
  - era5_2015
  - alibaba_cluster_trace_2018
  - cmip6_1930
  - uber_tlc_hourly
  - era5_2012
  - cmip6_1940
  - bdg-2_rat
  - era5_2018
  - largest_2020
  - cmip6_1875
  - cmip6_1905
  - borg_cluster_data_2011
  - tourism_yearly
  - traffic_weekly
  - largest_2018
  - PEMS07
  - era5_2001
  - cif_2016_6
  - era5_1996
  - bdg-2_panther
  - cmip6_1985
  - monash_m3_yearly
  - bitcoin_with_missing
  - era5_1998
  - era5_1992
  - favorita_sales
  - cmip6_1965
  - hog
  - era5_2005
  - cmip6_1850
  - PEMS03
  - cmip6_1920
  - covid19_energy
  - LOS_LOOP
  - cmip6_1895
  - tourism_quarterly
  - extended_web_traffic_with_missing
  - subseasonal_precip
  - cmip6_2005
  - era5_2016
  - azure_vm_traces_2017
  - taxi_30min
  - favorita_transactions
  - smart
  - kdd2022
  - gfc17_load
  - cif_2016_12
  - era5_2011
  - borealis
  - godaddy
  - cmip6_1995
  - vehicle_trips_with_missing
  - nn5_weekly
  - era5_2002
  - pedestrian_counts
  - era5_2008
  - PEMS04
  - cmip6_1950
  - ideal
  - cmip6_1865
  - residential_load_power
  - era5_1995
  - cmip6_1915
  - cmip6_1855
  - beijing_air_quality
  - era5_2000
  - cmip6_1925
  - china_air_quality
  - kaggle_web_traffic_weekly
  - cdc_fluview_ilinet
  - era5_1997
  - cmip6_1960
  - cmip6_2000
  - era5_2013
  - nn5_daily_with_missing
  - largest_2021
  - cmip6_1890
  - largest_2019
  - sunspot_with_missing
  - m5
  - elf
  - era5_1989
  - cmip6_1990
  - cockatoo
  - era5_2014
  - cmip6_1860
  - era5_1990
  - fred_md
  - cmip6_1910
  - monash_m3_other
  - era5_2007
  - cmip6_1955
  - subseasonal
  - traffic_hourly
  - monash_m3_monthly
  - cmip6_2010
  - era5_2009
  - wind_farms_with_missing
  - era5_2003
  - gfc14_load
  - project_tycho
  - bdg-2_bear
  - m1_monthly
  - cmip6_1880
  - era5_1994
  - era5_2010
  - cmip6_1935
  - australian_electricity_demand
  - m1_quarterly
  - pdb
  - lcl
  - cmip6_1970
  - oikolab_weather
  - cmip6_1870
  - cmip6_1900
  - largest_2017
  - tourism_monthly
  - HZMETRO
  - era5_2017
  - cmip6_1945
  - uber_tlc_daily
  - era5_1993
  - era5_1999
  - cmip6_1980
  - weather
  - rideshare_with_missing
  - PEMS08
  - era5_2004
  - sceaux
  - solar_power
  - m1_yearly
  - bdg-2_fox
  - Q-TRAFFIC
- domain: Energy
  term: short
  names:
  - bull
  - gfc12_load
  - buildings_900k
  - london_smart_meters_with_missing
  - residential_pv_power
  - wind_power
  - elecdemand
  - spain
  - bdg-2_rat
  - bdg-2_panther
  - hog
  - smart
  - kdd2022
  - gfc17_load
  - borealis
  - ideal
  - residential_load_power
  - elf
  - cockatoo
  - wind_farms_with_missing
  - gfc14_load
  - bdg-2_bear
  - australian_electricity_demand
  - pdb
  - lcl
  - sceaux
  - solar_power
  - bdg-2_fox
- domain: Energy
  term: medium
  names:
  - bull
  - gfc12_load
  - buildings_900k
  - london_smart_meters_with_missing
  - residential_pv_power
  - wind_power
  - elecdemand
  - spain
  - bdg-2_rat
  - bdg-2_panther
  - hog
  - smart
  - kdd2022
  - gfc17_load
  - borealis
  - ideal
  - residential_load_power
  - elf
  - cockatoo
  - wind_farms_with_missing
  - gfc14_load
  - bdg-2_bear
  - australian_electricity_demand
  - pdb
  - lcl
  - sceaux
  - solar_power
  - bdg-2_fox
- domain: Energy
  term: long
  names:
  - bull
  - gfc12_load
  - buildings_900k
  - london_smart_meters_with_missing
  - residential_pv_power
  - wind_power
  - elecdemand
  - spain
  - bdg-2_rat
  - bdg-2_panther
  - hog
  - smart
  - kdd2022
  - gfc17_load
  - borealis
  - ideal
  - residential_load_power
  - elf
  - cockatoo
  - wind_farms_with_missing
  - gfc14_load
  - bdg-2_bear
  - australian_electricity_demand
  - pdb
  - lcl
  - sceaux
  - solar_power
  - bdg-2_fox
- domain: Climate
  term: short
  names:
  - cmip6_1885
  - era5_1991
  - era5_2006
  - cmip6_1975
  - era5_2015
  - cmip6_1930
  - era5_2012
  - cmip6_1940
  - era5_2018
  - cmip6_1875
  - cmip6_1905
  - era5_2001
  - era5_1996
  - cmip6_1985
  - era5_1998
  - era5_1992
  - cmip6_1965
  - era5_2005
  - cmip6_1850
  - cmip6_1920
  - cmip6_1895
  - subseasonal_precip
  - cmip6_2005
  - era5_2016
  - era5_2011
  - cmip6_1995
  - era5_2002
  - era5_2008
  - cmip6_1950
  - cmip6_1865
  - era5_1995
  - cmip6_1915
  - cmip6_1855
  - era5_2000
  - cmip6_1925
  - era5_1997
  - cmip6_1960
  - cmip6_2000
  - era5_2013
  - cmip6_1890
  - era5_1989
  - cmip6_1990
  - era5_2014
  - cmip6_1860
  - era5_1990
  - cmip6_1910
  - era5_2007
  - cmip6_1955
  - subseasonal
  - cmip6_2010
  - era5_2009
  - era5_2003
  - cmip6_1880
  - era5_1994
  - era5_2010
  - cmip6_1935
  - cmip6_1970
  - oikolab_weather
  - cmip6_1870
  - cmip6_1900
  - era5_2017
  - cmip6_1945
  - era5_1993
  - era5_1999
  - cmip6_1980
  - weather
  - era5_2004
- domain: Climate
  term: medium
  names:
  - cmip6_1885
  - era5_1991
  - era5_2006
  - cmip6_1975
  - era5_2015
  - cmip6_1930
  - era5_2012
  - cmip6_1940
  - era5_2018
  - cmip6_1875
  - cmip6_1905
  - era5_2001
  - era5_1996
  - cmip6_1985
  - era5_1998
  - era5_1992
  - cmip6_1965
  - era5_2005
  - cmip6_1850
  - cmip6_1920
  - cmip6_1895
  - subseasonal_precip
  - cmip6_2005
  - era5_2016
  - era5_2011
  - cmip6_1995
  - era5_2002
  - era5_2008
  - cmip6_1950
  - cmip6_1865
  - era5_1995
  - cmip6_1915
  - cmip6_1855
  - era5_2000
  - cmip6_1925
  - era5_1997
  - cmip6_1960
  - cmip6_2000
  - era5_2013
  - cmip6_1890
  - era5_1989
  - cmip6_1990
  - era5_2014
  - cmip6_1860
  - era5_1990
  - cmip6_1910
  - era5_2007
  - cmip6_1955
  - subseasonal
  - cmip6_2010
  - era5_2009
  - era5_2003
  - cmip6_1880
  - era5_1994
  - era5_2010
  - cmip6_1935
  - cmip6_1970
  - oikolab_weather
  - cmip6_1870
  - cmip6_1900
  - era5_2017
  - cmip6_1945
  - era5_1993
  - era5_1999
  - cmip6_1980
  - weather
  - era5_2004
- domain: Climate
  term: long
  names:
  - cmip6_1885
  - era5_1991
  - era5_2006
  - cmip6_1975
  - era5_2015
  - cmip6_1930
  - era5_2012
  - cmip6_1940
  - era5_2018
  - cmip6_1875
  - cmip6_1905
  - era5_2001
  - era5_1996
  - cmip6_1985
  - era5_1998
  - era5_1992
  - cmip6_1965
  - era5_2005
  - cmip6_1850
  - cmip6_1920
  - cmip6_1895
  - subseasonal_precip
  - cmip6_2005
  - era5_2016
  - era5_2011
  - cmip6_1995
  - era5_2002
  - era5_2008
  - cmip6_1950
  - cmip6_1865
  - era5_1995
  - cmip6_1915
  - cmip6_1855
  - era5_2000
  - cmip6_1925
  - era5_1997
  - cmip6_1960
  - cmip6_2000
  - era5_2013
  - cmip6_1890
  - era5_1989
  - cmip6_1990
  - era5_2014
  - cmip6_1860
  - era5_1990
  - cmip6_1910
  - era5_2007
  - cmip6_1955
  - subseasonal
  - cmip6_2010
  - era5_2009
  - era5_2003
  - cmip6_1880
  - era5_1994
  - era5_2010
  - cmip6_1935
  - cmip6_1970
  - oikolab_weather
  - cmip6_1870
  - cmip6_1900
  - era5_2017
  - cmip6_1945
  - era5_1993
  - era5_1999
  - cmip6_1980
  - weather
  - era5_2004
- domain: Transport
  term: short
  names:
  - SHMETRO
  - BEIJING_SUBWAY_30MIN
  - PEMS_BAY
  - covid_mobility
  - uber_tlc_hourly
  - largest_2020
  - traffic_weekly
  - largest_2018
  - PEMS07
  - PEMS03
  - covid19_energy
  - LOS_LOOP
  - taxi_30min
  - vehicle_trips_with_missing
  - pedestrian_counts
  - PEMS04
  - largest_2021
  - largest_2019
  - traffic_hourly
  - largest_2017
  - HZMETRO
  - uber_tlc_daily
  - rideshare_with_missing
  - PEMS08
  - Q-TRAFFIC
- domain: Transport
  term: medium
  names:
  - SHMETRO
  - BEIJING_SUBWAY_30MIN
  - PEMS_BAY
  - covid_mobility
  - uber_tlc_hourly
  - largest_2020
  - traffic_weekly
  - largest_2018
  - PEMS07
  - PEMS03
  - covid19_energy
  - LOS_LOOP
  - taxi_30min
  - vehicle_trips_with_missing
  - pedestrian_counts
  - PEMS04
  - largest_2021
  - largest_2019
  - traffic_hourly
  - largest_2017
  - HZMETRO
  - uber_tlc_daily
  - rideshare_with_missing
  - PEMS08
  - Q-TRAFFIC
- domain: Transport
  term: long
  names:
  - SHMETRO
  - BEIJING_SUBWAY_30MIN
  - PEMS_BAY
  - covid_mobility
  - uber_tlc_hourly
  - largest_2020
  - traffic_weekly
  - largest_2018
  - PEMS07
  - PEMS03
  - covid19_energy
  - LOS_LOOP
  - taxi_30min
  - vehicle_trips_with_missing
  - pedestrian_counts
  - PEMS04
  - largest_2021
  - largest_2019
  - traffic_hourly
  - largest_2017
  - HZMETRO
  - uber_tlc_daily
  - rideshare_with_missing
  - PEMS08
  - Q-TRAFFIC
- domain: Web
  term: short
  names:
  - wiki-rolling_nips
  - extended_web_traffic_with_missing
  - kaggle_web_traffic_weekly
- domain: Web
  term: medium
  names:
  - wiki-rolling_nips
  - extended_web_traffic_with_missing
  - kaggle_web_traffic_weekly
- domain: Web
  term: long
  names:
  - wiki-rolling_nips
  - extended_web_traffic_with_missing
  - kaggle_web_traffic_weekly
- domain: Healthcare
  term: short
  names:
  - cdc_fluview_who_nrevss
  - cdc_fluview_ilinet
  - project_tycho
- domain: Econ/Fin
  term: short
  names:
  - monash_m3_quarterly
  - tourism_yearly
  - cif_2016_6
  - monash_m3_yearly
  - bitcoin_with_missing
  - tourism_quarterly
  - cif_2016_12
  - godaddy
  - nn5_weekly
  - nn5_daily_with_missing
  - fred_md
  - monash_m3_other
  - monash_m3_monthly
  - m1_monthly
  - m1_quarterly
  - tourism_monthly
  - m1_yearly
- domain: CloudOps
  term: short
  names:
  - alibaba_cluster_trace_2018
  - borg_cluster_data_2011
  - azure_vm_traces_2017
- domain: CloudOps
  term: medium
  names:
  - alibaba_cluster_trace_2018
  - borg_cluster_data_2011
  - azure_vm_traces_2017
- domain: CloudOps
  term: long
  names:
  - alibaba_cluster_trace_2018
  - borg_cluster_data_2011
  - azure_vm_traces_2017
- domain: Sales
  term: short
  names:
  - favorita_sales
  - favorita_transactions
  - m5
- domain: Nature
  term: short
  names:
  - beijing_air_quality
  - china_air_quality
  - sunspot_with_missing
- domain: Nature
  term: medium
  names:
  - beijing_air_quality
  - china_air_quality
  - sunspot_with_missing
- domain: Nature
  term: long
  names:
  - beijing_air_quality
  - china_air_quality
  - sunspot_with_missing
