defaults:
  - datasets: train_test
  - _self_


index: 0   
split: "train_test"  

hydra:
  run:
    dir: outputs/${hydra:job.name}/${name}/${datasets.name}/${split}
analyzer:
  _target_: gift_eval.analysis.Analyzer
  datasets: ${datasets.datasets}
  index: ${index} 
name: "test"
